import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Project from "../components/Project";
import Skills from "../components/Skills";
// import { Skill } from "../typings";

interface Props {
  skills: {
    id: number;
    name: string;
    iconeName: string;
    library: string;
    size: number;
    lvl: number;
    directionLeft?: boolean;
  }[];
  projects: {
    id: number;
    name: string;
    technos: {
      name: string;
      size: number;
    }[];
    text: string[];
    image: string;
  }[];
}
const Home = ({ skills, projects }: Props) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]">
      <Head>
        <title>Online CV</title>
        <meta name="description" content="Generated by Online CV" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="hero" className="snap-start">
        <Hero />
      </section>

      <section id="about" className="snap-center">
        <About />
      </section>

      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>

      <section id="project" className="snap-center">
        <Project projects={projects} />
      </section>

      <section id="contact" className="snap-start">
        <Contact />
      </section>

      <footer className="relative bottom-14 w-full text-center text-lg border-t-2 py-2">
        <div>
          <p>Remy Valentin </p>
        </div>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const resSkills = await fetch("http://localhost:3000/api/skills");
  const skills: Props = await resSkills.json();

  const resProj = await fetch("http://localhost:3000/api/projects");
  const projects: Props = await resProj.json();
  // console.log(skill);
  return {
    props: {
      skills,
      projects,
    },
  };
};

export default Home;
