import type { GetServerSideProps, GetStaticProps } from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Project from "../components/Project";
import SkillsComp from "../components/Skills";
import { Projects, Skills } from "../typings";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSkills } from "../utils/fetchSkills";

type Props = {
  skills: Skills[];
  projects: Projects[];
};
const Home = ({ skills, projects }: Props) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]">
      <Head>
        <title>Online CV</title>
        <meta name="description" content="Generated by Online CV" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="hero" className="snap-start">
        <Hero />
      </section>

      <section id="about" className="snap-center">
        <About />
      </section>

      <section id="skills" className="snap-start">
        <SkillsComp skills={skills} />
      </section>

      <section id="project" className="snap-center">
        <Project projects={projects} />
      </section>

      <section id="contact" className="snap-start">
        <Contact />
      </section>

      <footer className="relative bottom-14 w-full text-center text-lg border-t-2 py-2 border-gray-600">
        <div>
          <p className="text-gray-400">Remy Valentin</p>
        </div>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const skills: Skills[] = await fetchSkills();
  const projects: Projects[] = await fetchProjects();
  return {
    props: {
      skills,
      projects,
    },
  };
};

export default Home;
